apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v3
        name: vote

